# -*- coding: utf-8 -*-
"""utsaksa3ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rOun0sVyhb9G9LobHd6GcvtaWnC0XIE-
"""

import numpy as np
import pandas as pd
import seaborn as sns  # Add import statement for seaborn

filePath = 'https://raw.githubusercontent.com/aksajr/aksa/main/heart.csv'

# Baca file CSV ke dalam dataframe
df = pd.read_csv(filePath)

df.head()

df.info()

num = ['age' , 'sex', 'cp', 'trestbps', 'chol',  'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

df[num].describe()

df.corr()

# Membuat plot countplot menggunakan Seaborn
sns.countplot(data=df, x="age", hue="target")

df.head()

x = df.drop(['target'], axis=1)  # Variabel Numerik (Independen)
y = df['target']  # Variabel Dependen

from sklearn.model_selection import train_test_split

#Split data set menjadi 80:20
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Standardize the features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

x_train.shape, x_test.shape

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

#membuat model logistic regression
logreg = LogisticRegression()

# melatih model
logreg.fit(x_train, y_train)

# membuat variabel prediksi
y_pred = logreg.predict(x_test)

# menghitung nilai accuracy model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of Logistic Regression model:", accuracy)
